
---
deployment:
      tasks:
        - export DEPLOYPATH=/home/sc2bobe7404/excel  	  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
